name: gallery_saver_example
description: Demonstrates how to use the gallery_saver plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  image_picker: ^0.7.0-nullsafety
  path_provider: ^2.0.0-nullsafety.1
  http: ^0.13.0-nullsafety.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  gallery_saver:
    path: ../

flutter:
  uses-material-design: true
